<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Carbon\Carbon;

class GeminiService
{
    protected $apiKey;
    protected $apiUrl;

    public function __construct()
    {
        $this->apiKey = config('services.gemini.key');
        $this->apiUrl = config('services.gemini.url');
    }

    public function generateReadme($repoName, $description, $language, $files = [], $fileContents = [])
    {
        $fileList = implode(', ', $files);

        $generationDate = now()->format('d-m-Y');
        $generationLocation = 'India';

        $deepContextBlock = "";
        if (!empty($fileContents)) {
            $deepContextBlock = "\n\nDeep Context (Raw File Contents for Analysis):\n";
            foreach ($fileContents as $fileName => $content) {
                $deepContextBlock .= "--- {$fileName} ---\n```\n{$content}\n```\n\n";
            }
            $deepContextBlock .= "Please use the Deep Context above to extract precise dependencies, exact installation commands (like npm install or composer install), and architecture details for the README.\n";
        }

        $prompt = "Act as an Expert Developer Advocate and Technical Writer. 
        I need a professional, highly readable README.md file for a GitHub project. The Markdown should feel like a premium SaaS product or a top-tier open-source library.
        
        Project Details:
        - Project Name: {$repoName}
        - Description: {$description}
        - Main Language: {$language}
        - Key Files/Directories: {$fileList}{$deepContextBlock}
        
        Formatting & UI Requirements:
        1. Hero Section: Start with an `<h1>` header, centered text, and a concise 1-sentence catchphrase.
        2. Badges: Include top-level Shields.io badges for the Tech Stack ({$language}), License (MIT), and Build Status.
        3. Table of Contents: Create a clickable Table of Contents for easy navigation.
        4. Visuals: Include a placeholder block for a project screenshot `![Project Preview](docs/preview.png)`.
        5. Clean Structure: Use horizontal rules (`---`), blockquotes (`>`) for important notes, and bolding for emphasis.
        6. Installation: Write clear, step-by-step installation instructions with proper bash code blocks assuming standard {$language} setup steps.
        7. Folder Structure: Provide a brief Markdown tree representation based on the 'Key Files' provided above.
        8. Watermark Footer: At the very bottom of the document, add a horizontal rule followed by exactly this italicized text: '*Documentation automatically generated by GitScribe on {$generationDate} ({$generationLocation}).*'
        
        CRITICAL: Output ONLY the raw Markdown code. Do not include any conversational filler before or after the code block.";

        $response = Http::timeout(120)->post($this->apiUrl . '?key=' . $this->apiKey, [
            'contents' => [
                [
                    'parts' => [
                        ['text' => $prompt]
                    ]
                ]
            ]
        ]);

        if ($response->successful()) {
            return $response->json()['candidates'][0]['content']['parts'][0]['text'];
        }

        return "Failed to generate README. Please try again.";
    }

    public function generateReadmeFromDiff($repoName, $oldReadme, $diff)
    {
        $prompt = "Act as an Expert Developer Advocate and Technical Writer. 
        You are managing the documentation for the GitHub project: {$repoName}.
        
        The developer just pushed new code. Below is the ORIGINAL README.md and the DIFF of the recent code changes.
        
        Task: Update the ORIGINAL README.md to reflect the new features, dependencies, or architectural changes introduced in the DIFF. 
        Keep the overall style, tone, and existing valid information intact. Only modify or add sections that are relevant to the new changes.
        
        ### ORIGINAL README ###
        ```markdown
        {$oldReadme}
        ```
        
        ### RECENT CODE CHANGES (DIFF) ###
        ```diff
        {$diff}
        ```
        
        CRITICAL: Output ONLY the raw updated Markdown code. Do not include any conversational filler before or after the code block.";

        $response = Http::timeout(120)->post($this->apiUrl . '?key=' . $this->apiKey, [
            'contents' => [
                [
                    'parts' => [
                        ['text' => $prompt]
                    ]
                ]
            ]
        ]);

        if ($response->successful()) {
            return $response->json()['candidates'][0]['content']['parts'][0]['text'];
        }

        return "Failed to generate updated README. Please try again.";
    }
}