<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class PullRequestController extends Controller
{
    //
    public function push(Request $request)
    {
        $user = auth()->user();
        $owner = $request->input('owner');
        $repo = $request->input('repo');
        
        $content = base64_decode($request->input('content')); 
        
        $token = $user->github_token;
        $baseUrl = "https://api.github.com/repos/{$owner}/{$repo}";

        try {
            $repoData = Http::withToken($token)->get($baseUrl)->json();
            $defaultBranch = $repoData['default_branch'];

            $branchData = Http::withToken($token)->get("{$baseUrl}/git/ref/heads/{$defaultBranch}")->json();
            $baseSha = $branchData['object']['sha'];

            $newBranchName = 'gitscribe-readme-' . time();
            Http::withToken($token)->post("{$baseUrl}/git/refs", [
                'ref' => "refs/heads/{$newBranchName}",
                'sha' => $baseSha
            ]);

            $fileCheck = Http::withToken($token)->get("{$baseUrl}/contents/README.md");
            $fileSha = $fileCheck->successful() ? $fileCheck->json()['sha'] : null;

            $commitPayload = [
                'message' => '📝 Docs: Add AI-generated README via GitScribe',
                'content' => base64_encode($content),
                'branch' => $newBranchName
            ];
            
            if ($fileSha) {
                $commitPayload['sha'] = $fileSha; 
            }

            Http::withToken($token)->put("{$baseUrl}/contents/README.md", $commitPayload);

            $prResponse = Http::withToken($token)->post("{$baseUrl}/pulls", [
                'title' => '✨ Update README.md (GitScribe)',
                'body' => "This Pull Request was automatically generated by **GitScribe AI**.\n\nPlease review the documentation changes before merging.",
                'head' => $newBranchName,
                'base' => $defaultBranch
            ]);

            if ($prResponse->successful()) {
                return redirect($prResponse->json()['html_url']);
            }

            return redirect()->route('dashboard')->with('error', 'Failed to create Pull Request. GitHub rejected the request.');

        } catch (\Exception $e) {
            return redirect()->route('dashboard')->with('error', 'An error occurred while communicating with GitHub.');
        }
    }
}
