<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class PullRequestController extends Controller
{
    //
    public function push(Request $request, \App\Services\GitHubService $githubService)
    {
        $user = auth()->user();
        $owner = $request->input('owner');
        $repo = $request->input('repo');
        
        $content = base64_decode($request->input('content')); 
        $token = $user->github_token; 

        try {
            $commitMessage = '📝 Docs: Add AI-generated README via GitScribe';
            $prTitle = '✨ Update README.md (GitScribe)';
            $prBody = "This Pull Request was automatically generated by **GitScribe AI**.\n\nPlease review the documentation changes before merging.";

            $prResponse = $githubService->createPullRequest($token, $owner, $repo, $content, $commitMessage, $prTitle, $prBody);

            if ($prResponse->successful()) {
                return redirect($prResponse->json()['html_url']);
            }

            return redirect()->route('dashboard')->with('error', 'Failed to create Pull Request. GitHub rejected the request.');

        } catch (\Exception $e) {
            return redirect()->route('dashboard')->with('error', $e->getMessage());
        }
    }
}
