<?php

namespace App\Jobs;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\Log;
use App\Services\GeminiService;
use App\Services\GitHubService;
use App\Models\User;

class GenerateWikiJob implements ShouldQueue
{
    use Queueable;

    public $timeout = 600; 
    public $tries = 3;

    protected $user;
    protected $owner;
    protected $repo;

    public function __construct(User $user, $owner, $repo)
    {
        $this->user = $user;
        $this->owner = $owner;
        $this->repo = $repo;
    }

    public function handle(GeminiService $gemini, GitHubService $githubService)
    {
        $token = $this->user->github_token;
        
        $meta = $githubService->getRepoMeta($token, $this->owner, $this->repo);
        $repoName = $meta['name'] ?? $this->repo;
        $defaultBranch = $meta['default_branch'] ?? 'main';

        $tree = $githubService->getRepoTree($token, $this->owner, $this->repo, $defaultBranch);
        $limitedTree = array_map(function($node) { return $node['path']; }, array_slice($tree, 0, 500));

        // 1. Plan Architecture
        $wikiPages = $gemini->planWikiArchitecture($repoName, json_encode($limitedTree));
        
        if (empty($wikiPages)) {
            Log::error("Failed to plan wiki architecture for {$this->owner}/{$this->repo}");
            return;
        }

        $generatedFiles = [];

        // 2. Loop & Write
        foreach ($wikiPages as $pageTopic) {
            $filesToRead = $gemini->pickFilesForWikiPage($repoName, $pageTopic, json_encode($limitedTree));
            
            $fileContents = [];
            foreach ($filesToRead as $filePath) {
                $content = $githubService->getFileContent($token, $this->owner, $this->repo, $filePath);
                if ($content) {
                    $fileContents[$filePath] = \Illuminate\Support\Str::limit($content, 2000);
                }
            }

            $markdown = $gemini->writeWikiPage($repoName, $pageTopic, $fileContents);
            $filename = 'docs/' . \Illuminate\Support\Str::slug($pageTopic) . '.md';
            
            $generatedFiles[$filename] = $markdown;
        }

        // 3. Publish via PR
        $githubService->createWikiPullRequest(
            $token, 
            $this->owner, 
            $this->repo, 
            $generatedFiles, 
            "📚 Docs: Autogenerated Project Wiki",
            "📚 Docs: Autogenerated Project Wiki",
            "This Pull Request contains a complete, autogenerated Wiki for the project, placed in the `docs/` folder.\n\nGenerated by **GitScribe**."
        );
    }
}
