<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use App\Models\Webhook;
use App\Services\GitHubService;
use App\Services\GeminiService;
use Illuminate\Support\Facades\Log;

class ProcessGithubPushJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $timeout = 120; // Allow 2 minutes for API processing

    protected $webhook;
    protected $payload;

    /**
     * Create a new job instance.
     */
    public function __construct(Webhook $webhook, array $payload)
    {
        $this->webhook = $webhook;
        $this->payload = $payload;
    }

    /**
     * Execute the job.
     */
    public function handle(GitHubService $githubService, GeminiService $geminiService): void
    {
        try {
            $user = $this->webhook->user;
            $token = $user->github_token;
            
            $repoParts = explode('/', $this->webhook->repo_full_name);
            $owner = $repoParts[0];
            $repo = $repoParts[1];

            $before = $this->payload['before'] ?? null;
            $after = $this->payload['after'] ?? null;

            if (!$before || !$after || $before === '0000000000000000000000000000000000000000') {
                Log::info("Skipping diff generation: Missing valid before/after SHAs.");
                return;
            }

            // 1. Fetch the diff
            $diff = $githubService->getCompareDiff($token, $owner, $repo, $before, $after);
            
            if (!$diff) {
                Log::warning("Failed to fetch diff for {$owner}/{$repo}");
                return;
            }

            // 2. Fetch the old README
            $readmeResponse = $githubService->getFileContent($token, $owner, $repo, 'README.md');
            $oldReadme = $readmeResponse ? $readmeResponse : '';

            // If there's no old README, we can't really "update" it via diff intelligently, 
            // but we'll let Gemini try or just return. For now, let's proceed.

            // Limit diff size to prevent massive prompts
            $diff = \Illuminate\Support\Str::limit($diff, 8000);

            // 3. Generate updated README via Gemini
            $newReadmeContent = $geminiService->generateReadmeFromDiff($repo, $oldReadme, $diff);

            // 4. Open Pull Request
            $commitMessage = '📝 Docs: Auto-update README via GitScribe Webhook';
            $prTitle = '✨ Auto-Update README.md (GitScribe)';
            $prBody = "This Pull Request was automatically generated by **GitScribe AI** in response to your recent push.\n\nIt analyzes the diff of your code changes and updates the documentation accordingly.";

            $githubService->createPullRequest($token, $owner, $repo, $newReadmeContent, $commitMessage, $prTitle, $prBody);
            
            Log::info("Successfully processed webhook push and opened PR for {$owner}/{$repo}");

        } catch (\Exception $e) {
            Log::error("Failed to process Github Push Job: " . $e->getMessage(), ['trace' => $e->getTraceAsString()]);
        }
    }
}
